### PR TITLE
fix: Typo

### PR DESCRIPTION
**Pull request by ezaurum**
## what
* Change aws_iam_role name in README.md

## why
* To fix cannot find reference error inside example

### CODE REVIEW

**Review by aknysh — COMMENTED** [review]
@ezaurum thanks for the PR.

It does not look like the affected files have anything for `aws_iam_role` (as the PR description mentions)

**Comment by ezaurum** [comment]
I am sorry. I updated PR message. I changed example's typo.

**Review by aknysh — APPROVED** [review]

**Comment by ezaurum** [comment]
@aknysh I am sorry again. Maybe my commit reverted by bot.
Did I something wrong?
This is my commit https://github.com/cloudposse/terraform-aws-ecr-public/pull/6/commits/8f04e7c1294cc5c163b4ae6674fb204478b37bad

**Pull request merged**
